function [Const] = return_ref_chan(EEG_LOC, Const)


if strcmp(EEG_LOC, 'C3_POz')
    Const.EEG_chan = get_chan_idx(Const, 'C3'); 
    Const.REF_CHAN = get_chan_idx(Const, 'POz'); 

elseif strcmp(EEG_LOC, 'C4_POz')
    Const.EEG_chan = get_chan_idx(Const, 'C4'); 
    Const.REF_CHAN = get_chan_idx(Const, 'POz'); 

elseif strcmp(EEG_LOC, 'C3_local')
    Const.EEG_chan = get_chan_idx(Const, 'C3'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'FC5'), ...
                      get_chan_idx(Const, 'FC1'), ...
                      get_chan_idx(Const, 'CP5'), ...
                      get_chan_idx(Const, 'CP1')]; 

elseif strcmp(EEG_LOC, 'C4_local')
    Const.EEG_chan = get_chan_idx(Const, 'C4'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'FC6'), ...
                      get_chan_idx(Const, 'FC2'), ...
                      get_chan_idx(Const, 'CP6'), ...
                      get_chan_idx(Const, 'CP2')]; 

elseif strcmp(EEG_LOC, 'CP1_local')
    Const.EEG_chan = get_chan_idx(Const, 'CP1'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'Cz'), ...
                      get_chan_idx(Const, 'C3'), ...
                      get_chan_idx(Const, 'Pz'), ...
                      get_chan_idx(Const, 'P3')]; 
                  
elseif strcmp(EEG_LOC, 'CP2_local')
    Const.EEG_chan = get_chan_idx(Const, 'CP2'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'Cz'), ...
                      get_chan_idx(Const, 'C4'), ...
                      get_chan_idx(Const, 'Pz'), ...
                      get_chan_idx(Const, 'P4')]; 

elseif strcmp(EEG_LOC, 'CP5_local')
    Const.EEG_chan = get_chan_idx(Const, 'CP5'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'T7'), ...
                      get_chan_idx(Const, 'C3'), ...
                      get_chan_idx(Const, 'P3'), ...
                      get_chan_idx(Const, 'P7')]; 

elseif strcmp(EEG_LOC, 'CP6_local')
    Const.EEG_chan = get_chan_idx(Const, 'CP6'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'C4'), ...
                      get_chan_idx(Const, 'T8'), ...
                      get_chan_idx(Const, 'P4'), ...
                      get_chan_idx(Const, 'P8')]; 

elseif strcmp(EEG_LOC, 'P3_local')
    Const.EEG_chan = get_chan_idx(Const, 'P3'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'CP5'), ...
                      get_chan_idx(Const, 'CP1'), ...
                      get_chan_idx(Const, 'Pz'), ...
                      get_chan_idx(Const, 'P7')]; 

elseif strcmp(EEG_LOC, 'P4_local')
    Const.EEG_chan = get_chan_idx(Const, 'P4'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'CP2'), ...
                      get_chan_idx(Const, 'CP6'), ...
                      get_chan_idx(Const, 'Pz'), ...
                      get_chan_idx(Const, 'P8')]; 

elseif strcmp(EEG_LOC, 'FC1_local')
    Const.EEG_chan = get_chan_idx(Const, 'FC1'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'F3'), ...
                      get_chan_idx(Const, 'Fz'), ...
                      get_chan_idx(Const, 'C3'), ...
                      get_chan_idx(Const, 'Cz')]; 

elseif strcmp(EEG_LOC, 'FC2_local')
    Const.EEG_chan = get_chan_idx(Const, 'FC2'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'Fz'), ...
                      get_chan_idx(Const, 'F4'), ...
                      get_chan_idx(Const, 'Cz'), ...
                      get_chan_idx(Const, 'C4')]; 

elseif strcmp(EEG_LOC, 'F3_local')
    Const.EEG_chan = get_chan_idx(Const, 'F3'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'F7'), ...
                      get_chan_idx(Const, 'FC5'), ...
                      get_chan_idx(Const, 'FC1'), ...
                      get_chan_idx(Const, 'Fz')]; 

elseif strcmp(EEG_LOC, 'F4_local')
    Const.EEG_chan = get_chan_idx(Const, 'F4'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'Fz'), ...
                      get_chan_idx(Const, 'FC2'), ...
                      get_chan_idx(Const, 'FC6'), ...
                      get_chan_idx(Const, 'F8')]; 

elseif strcmp(EEG_LOC, 'POz_local')
    Const.EEG_chan = get_chan_idx(Const, 'POz'); 
    Const.REF_CHAN = [get_chan_idx(Const, 'O1'), ...
                      get_chan_idx(Const, 'O2'), ...
                      get_chan_idx(Const, 'P3'), ...
                      get_chan_idx(Const, 'P4')]; 
end